version: '3'

volumes:
  data:
  mysql-data:

services:
  app:
    build: .
    image: base-wordpress:5-apache
    ports:
      - "8000:80"
    env_file:
      - ./.env
    volumes:
#      - ".:/var/www/html" # Uncomment to develop locally
      - "data:/data"
    depends_on:
        - mysql

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${ARTIFAKT_MYSQL_DATABASE_NAME:-changeme}
      MYSQL_USER: ${ARTIFAKT_MYSQL_USER:-changeme}
      MYSQL_PASSWORD: ${ARTIFAKT_MYSQL_PASSWORD:-s3cr3t!}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
        - "3306:3306"